services:
  django-app:
    image: haider57/backend-service:latest
    container_name: django-app
    expose:
      - 8000
    environment:
      - DEBUG=False

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django-app