name: Run Unit & Lint Test

on:
  push:
    branches:
      - 'feature/*'

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          
      - name: Run flake8 linter
        run: |
          git fetch origin feature/django-app --depth=1
          CHANGED_FILES=$(git diff --name-only FETCH_HEAD HEAD -- '*.py')
          echo "$CHANGED_FILES"
          if [ -n "$CHANGED_FILES" ]; then
            cd app
            flake8 $CHANGED_FILES
          else
            echo "No Python files changed."
          fi
  
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose build

      - name: Run Unit Tests
        run: docker compose run --rm app sh -c "python manage.py test"
