name: Run Unit & Lint Test

on:
  push:
    branches:
      - 'feature/*'

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8 linter
        run: |
          git fetch origin feature/django-app --depth=1
          CHANGED_FILES=$(git diff --name-only FETCH_HEAD HEAD -- '*.py')
          echo "$CHANGED_FILES"
          if [ -n "$CHANGED_FILES" ]; then
            cd app
            flake8 $CHANGED_FILES
          else
            echo "No Python files changed."
          fi
  
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker compose build

      - name: Run Unit Tests
        run: docker compose -f docker-compose.yml run --rm app sh -c "python manage.py test"

  merge_to_dev:
    runs-on: ubuntu-latest
    needs: [lint, unit_test]
    if: ${{ needs.lint.result == 'success' && needs.unittest.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git credentials
        run: |
          git config --global user.email haider.sde@gmail.com
          git config --global user.name "haider"

      - name: Get branch name
        id: get_branch
        run: |
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Checkout dev branch
        run: |
          git fetch origin dev
          git checkout dev
          git pull origin dev

      - name: Fetch feature branch
        run: |
          git fetch origin ${{ env.BRANCH_NAME }}
          git checkout ${{ env.BRANCH_NAME }}

      - name: Attempt to Merge Feature Branch into Dev
        run: |
          git checkout dev
          git merge --no-ff ${{ env.BRANCH_NAME }} || {
            echo "Merge failed. Details:";
            git status;
            git diff;
            exit 1;
          }

      - name: Push changes to dev
        if: success()
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git push origin dev